# Generated by Django 5.1.4 on 2025-01-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("resume_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "resume",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("template_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "templates",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resume"
                    ),
                ),
            ],
            options={
                "db_table": "sections",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("content_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.section"
                    ),
                ),
            ],
            options={
                "db_table": "content",
            },
        ),
        migrations.CreateModel(
            name="ResumeToTemplate",
            fields=[
                ("mapping_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resume"
                    ),
                ),
                (
                    "template_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.template"
                    ),
                ),
            ],
            options={
                "db_table": "resume_to_template",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
    ]
